//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzariaDoZe.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PizzariaDoZe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_circle_FILL0_wght400_GRAD0_opsz48 {
            get {
                object obj = ResourceManager.GetObject("add_circle_FILL0_wght400_GRAD0_opsz48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap badge_FILL0_wght400_GRAD0_opsz48 {
            get {
                object obj = ResourceManager.GetObject("badge_FILL0_wght400_GRAD0_opsz48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acessar.
        /// </summary>
        internal static string btnAcessar_Text {
            get {
                return ResourceManager.GetString("btnAcessar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bebidas.
        /// </summary>
        internal static string btnBebida_Text {
            get {
                return ResourceManager.GetString("btnBebida.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        internal static string btnBuscar_Text {
            get {
                return ResourceManager.GetString("btnBuscar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string btnCancelar_Text {
            get {
                return ResourceManager.GetString("btnCancelar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        internal static string btnCliente_Text {
            get {
                return ResourceManager.GetString("btnCliente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        internal static string btnConfigurar_Text {
            get {
                return ResourceManager.GetString("btnConfigurar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereços.
        /// </summary>
        internal static string btnEndereco_Text {
            get {
                return ResourceManager.GetString("btnEndereco.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionários.
        /// </summary>
        internal static string btnFuncionario_Text {
            get {
                return ResourceManager.GetString("btnFuncionario.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredientes.
        /// </summary>
        internal static string btnIngrediente_Text {
            get {
                return ResourceManager.GetString("btnIngrediente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedidos.
        /// </summary>
        internal static string btnPedido_Text {
            get {
                return ResourceManager.GetString("btnPedido.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabores.
        /// </summary>
        internal static string btnSabor_Text {
            get {
                return ResourceManager.GetString("btnSabor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        internal static string btnSalvar_Text {
            get {
                return ResourceManager.GetString("btnSalvar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valores.
        /// </summary>
        internal static string btnValor_Text {
            get {
                return ResourceManager.GetString("btnValor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_de_tela_2023_08_15_224831 {
            get {
                object obj = ResourceManager.GetObject("Captura de tela 2023-08-15 224831", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap category_FILL0_wght400_GRAD0_opsz48 {
            get {
                object obj = ResourceManager.GetObject("category_FILL0_wght400_GRAD0_opsz48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_FILL0_wght400_GRAD0_opsz48 {
            get {
                object obj = ResourceManager.GetObject("delete_FILL0_wght400_GRAD0_opsz48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_FILL0_wght400_GRAD0_opsz48 {
            get {
                object obj = ResourceManager.GetObject("edit_FILL0_wght400_GRAD0_opsz48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap extension_FILL0_wght400_GRAD0_opsz48 {
            get {
                object obj = ResourceManager.GetObject("extension_FILL0_wght400_GRAD0_opsz48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap group_FILL0_wght400_GRAD0_opsz48 {
            get {
                object obj = ResourceManager.GetObject("group_FILL0_wght400_GRAD0_opsz48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home_FILL0_wght400_GRAD0_opsz48 {
            get {
                object obj = ResourceManager.GetObject("home_FILL0_wght400_GRAD0_opsz48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 l.
        /// </summary>
        internal static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.5 l.
        /// </summary>
        internal static string label15_Text {
            get {
                return ResourceManager.GetString("label15.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 150 ml.
        /// </summary>
        internal static string label150_Text {
            get {
                return ResourceManager.GetString("label150.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 l.
        /// </summary>
        internal static string label2_Text {
            get {
                return ResourceManager.GetString("label2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 350 ml.
        /// </summary>
        internal static string label350_Text {
            get {
                return ResourceManager.GetString("label350.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 ml.
        /// </summary>
        internal static string label500_Text {
            get {
                return ResourceManager.GetString("label500.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 600 ml.
        /// </summary>
        internal static string label600_Text {
            get {
                return ResourceManager.GetString("label600.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro:.
        /// </summary>
        internal static string labelBairro_Text {
            get {
                return ResourceManager.GetString("labelBairro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        internal static string labelCategoria_Text {
            get {
                return ResourceManager.GetString("labelCategoria.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP: .
        /// </summary>
        internal static string labelCep_Text {
            get {
                return ResourceManager.GetString("labelCep.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade: .
        /// </summary>
        internal static string labelCidade_Text {
            get {
                return ResourceManager.GetString("labelCidade.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNH:.
        /// </summary>
        internal static string labelCNH_Text {
            get {
                return ResourceManager.GetString("labelCNH.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complemento:.
        /// </summary>
        internal static string labelComplemento_Text {
            get {
                return ResourceManager.GetString("labelComplemento.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF: .
        /// </summary>
        internal static string labelCPF_Text {
            get {
                return ResourceManager.GetString("labelCPF.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email: .
        /// </summary>
        internal static string labelEmail_Text {
            get {
                return ResourceManager.GetString("labelEmail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entregador.
        /// </summary>
        internal static string labelEntregador_Text {
            get {
                return ResourceManager.GetString("labelEntregador.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo.
        /// </summary>
        internal static string labelGrupo_Text {
            get {
                return ResourceManager.GetString("labelGrupo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredientes:.
        /// </summary>
        internal static string labelIngredientes_Text {
            get {
                return ResourceManager.GetString("labelIngredientes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logradouro: .
        /// </summary>
        internal static string labelLogradouro_Text {
            get {
                return ResourceManager.GetString("labelLogradouro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrícula: .
        /// </summary>
        internal static string labelMatricula_Text {
            get {
                return ResourceManager.GetString("labelMatricula.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome: .
        /// </summary>
        internal static string labelNome_Text {
            get {
                return ResourceManager.GetString("labelNome.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número:.
        /// </summary>
        internal static string labelNumero_Text {
            get {
                return ResourceManager.GetString("labelNumero.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observações: .
        /// </summary>
        internal static string labelObs_Text {
            get {
                return ResourceManager.GetString("labelObs.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País: .
        /// </summary>
        internal static string labelPais_Text {
            get {
                return ResourceManager.GetString("labelPais.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha: .
        /// </summary>
        internal static string labelSenha_Text {
            get {
                return ResourceManager.GetString("labelSenha.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho.
        /// </summary>
        internal static string labelTamanho_Text {
            get {
                return ResourceManager.GetString("labelTamanho.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone: .
        /// </summary>
        internal static string labelTelefone_Text {
            get {
                return ResourceManager.GetString("labelTelefone.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string labelTipo_Text {
            get {
                return ResourceManager.GetString("labelTipo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tela Inicial.
        /// </summary>
        internal static string labelTipoCadastro_Text {
            get {
                return ResourceManager.GetString("labelTipoCadastro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Bebidas.
        /// </summary>
        internal static string labelTipoCadastroBebida {
            get {
                return ResourceManager.GetString("labelTipoCadastroBebida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Clientes.
        /// </summary>
        internal static string labelTipoCadastroCliente {
            get {
                return ResourceManager.GetString("labelTipoCadastroCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Endereços.
        /// </summary>
        internal static string labelTipoCadastroEndereco {
            get {
                return ResourceManager.GetString("labelTipoCadastroEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Funcionários.
        /// </summary>
        internal static string labelTipoCadastroFuncionario {
            get {
                return ResourceManager.GetString("labelTipoCadastroFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Ingredientes.
        /// </summary>
        internal static string labelTipoCadastroIngrediente {
            get {
                return ResourceManager.GetString("labelTipoCadastroIngrediente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Pedidos.
        /// </summary>
        internal static string labelTipoCadastroPedido {
            get {
                return ResourceManager.GetString("labelTipoCadastroPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Sabores.
        /// </summary>
        internal static string labelTipoCadastroSabor {
            get {
                return ResourceManager.GetString("labelTipoCadastroSabor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Valores.
        /// </summary>
        internal static string labelTipoCadastroValor {
            get {
                return ResourceManager.GetString("labelTipoCadastroValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado: .
        /// </summary>
        internal static string labelUF_Text {
            get {
                return ResourceManager.GetString("labelUF.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        internal static string labelUsuario_Text {
            get {
                return ResourceManager.GetString("labelUsuario.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validade:.
        /// </summary>
        internal static string labelValidade_Text {
            get {
                return ResourceManager.GetString("labelValidade.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor: .
        /// </summary>
        internal static string labelValor_Text {
            get {
                return ResourceManager.GetString("labelValor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Adicional de Borda:.
        /// </summary>
        internal static string labelValorBorda_Text {
            get {
                return ResourceManager.GetString("labelValorBorda.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string lblIdioma_Text {
            get {
                return ResourceManager.GetString("lblIdioma.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap liquor_FILL0_wght400_GRAD0_opsz48 {
            get {
                object obj = ResourceManager.GetObject("liquor_FILL0_wght400_GRAD0_opsz48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap list_alt_FILL0_wght400_GRAD0_opsz48 {
            get {
                object obj = ResourceManager.GetObject("list_alt_FILL0_wght400_GRAD0_opsz48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap local_pizza_FILL0_wght400_GRAD0_opsz48 {
            get {
                object obj = ResourceManager.GetObject("local_pizza_FILL0_wght400_GRAD0_opsz48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador.
        /// </summary>
        internal static string rbAdmin_Text {
            get {
                return ResourceManager.GetString("rbAdmin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Água.
        /// </summary>
        internal static string rbAgua_Text {
            get {
                return ResourceManager.GetString("rbAgua.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atendente.
        /// </summary>
        internal static string rbAtendente_Text {
            get {
                return ResourceManager.GetString("rbAtendente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerveja.
        /// </summary>
        internal static string rbCerveja_Text {
            get {
                return ResourceManager.GetString("rbCerveja.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doce.
        /// </summary>
        internal static string rbDoce_Text {
            get {
                return ResourceManager.GetString("rbDoce.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entregador.
        /// </summary>
        internal static string rbEntregador_Text {
            get {
                return ResourceManager.GetString("rbEntregador.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especial.
        /// </summary>
        internal static string rbEspecial_Text {
            get {
                return ResourceManager.GetString("rbEspecial.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Família.
        /// </summary>
        internal static string rbFamilia_Text {
            get {
                return ResourceManager.GetString("rbFamilia.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grande.
        /// </summary>
        internal static string rbGrande_Text {
            get {
                return ResourceManager.GetString("rbGrande.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Média.
        /// </summary>
        internal static string rbMedia_Text {
            get {
                return ResourceManager.GetString("rbMedia.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outros.
        /// </summary>
        internal static string rbOutros_Text {
            get {
                return ResourceManager.GetString("rbOutros.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pequena.
        /// </summary>
        internal static string rbPequena_Text {
            get {
                return ResourceManager.GetString("rbPequena.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refrigerante.
        /// </summary>
        internal static string rbRefri_Text {
            get {
                return ResourceManager.GetString("rbRefri.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salgada.
        /// </summary>
        internal static string rbSalgada_Text {
            get {
                return ResourceManager.GetString("rbSalgada.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suco.
        /// </summary>
        internal static string rbSuco_Text {
            get {
                return ResourceManager.GetString("rbSuco.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tradicional.
        /// </summary>
        internal static string rbTradicional_Text {
            get {
                return ResourceManager.GetString("rbTradicional.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap request_page_FILL0_wght400_GRAD0_opsz48 {
            get {
                object obj = ResourceManager.GetObject("request_page_FILL0_wght400_GRAD0_opsz48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Bebida.
        /// </summary>
        internal static string TelaBebidaFormText {
            get {
                return ResourceManager.GetString("TelaBebidaFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Cliente.
        /// </summary>
        internal static string TelaClienteFormText {
            get {
                return ResourceManager.GetString("TelaClienteFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        internal static string TelaConfiguracaoFormText {
            get {
                return ResourceManager.GetString("TelaConfiguracaoFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Endereço.
        /// </summary>
        internal static string TelaEnderecoFormText {
            get {
                return ResourceManager.GetString("TelaEnderecoFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Funcionário.
        /// </summary>
        internal static string TelaFuncionarioFormText {
            get {
                return ResourceManager.GetString("TelaFuncionarioFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Ingrediente.
        /// </summary>
        internal static string TelaIngredienteFormText {
            get {
                return ResourceManager.GetString("TelaIngredienteFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string TelaLoginFormText {
            get {
                return ResourceManager.GetString("TelaLoginFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizzaria do Zé.
        /// </summary>
        internal static string TelaPrincipalFormText {
            get {
                return ResourceManager.GetString("TelaPrincipalFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Sabor.
        /// </summary>
        internal static string TelaSaborFormText {
            get {
                return ResourceManager.GetString("TelaSaborFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Valores de Pizza.
        /// </summary>
        internal static string TelaValorFormText {
            get {
                return ResourceManager.GetString("TelaValorFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Yellow_Neon_Pizza_Restaurant_Logo {
            get {
                object obj = ResourceManager.GetObject("Yellow Neon Pizza Restaurant Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
